### ISSUE TITLE
关于tensorflow 数据可视化 bug 关于  tf.train.SummaryWriter("/Users/taw/logs", sess.graph) 报错 

### ISSUE THREAD

**Issue by bobeneba** [MorvanZhou/tutorials#27]
报错内容： 
Traceback (most recent call last):
  File "/Users/taw/PycharmProjects/stractTest/tensorTest4.py", line 46, in <module>
    writer = tf.train.SummaryWriter("/Users/taw/logs", sess.graph)
  File "/Users/taw/anaconda/lib/python2.7/site-packages/tensorflow/python/training/summary_io.py", line 82, in __init__
    self.add_graph(graph_def)
  File "/Users/taw/anaconda/lib/python2.7/site-packages/tensorflow/python/training/summary_io.py", line 128, in add_graph
    event = event_pb2.Event(wall_time=time.time(), graph_def=graph_def)
  File "/Users/taw/anaconda/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 519, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Users/taw/anaconda/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 450, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/Users/taw/anaconda/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 517, in init
    copy.MergeFrom(new_val)
  File "/Users/taw/anaconda/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1208, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected GraphDef got Graph. for field Event.graph_def

**Comment by bobeneba** [comment]
已经解决，tensorflow版本问题太低问题，升级版本
