### ISSUE TITLE
pip3 how to install tkinter !

### ISSUE THREAD

**Issue by liuguiyangnwpu** [MorvanZhou/tutorials#28]
/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/liuguiyang/Documents/CodeProj/PyProj/MLCourse/source/QLearn/maze/demo_maze.py
Traceback (most recent call last):
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/MLCourse/source/QLearn/maze/demo_maze.py", line 13, in <module>
    from source.QLearn.maze.maze_env import Maze
  File "/Users/liuguiyang/Documents/CodeProj/PyProj/MLCourse/source/QLearn/maze/maze_env.py", line 12, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by liuguiyangnwpu** [comment]
I have find the method to repair this program !

https://gist.github.com/liuguiyangnwpu/0afa91da2f0c6581321f8087719e008e

thx !
