### ISSUE TITLE
python2.7下怎么运行例程

### ISSUE THREAD

**Issue by py060301045** [MorvanZhou/tutorials#31]
莫烦老师您好！
    我是初学者，看了您的视频收获很大，讲行特别好，非常感谢您 的分享！
    我用python2.7运行您的例程tutorials/tensorflowTUT/tf14_tensorboard/
会报错，不知道该怎么改。报错如下：
Traceback (most recent call last):
  File "/home/py/文档/practice/tensorflow_Visualization2.py", line 46, in <module>
    writer = tf.train.SummaryWriter('logs/', sess.graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 82, in __init__
    self.add_graph(graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 128, in add_graph
    event = event_pb2.Event(wall_time=time.time(), graph_def=graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 519, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 450, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 517, in init
    copy.MergeFrom(new_val)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1208, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected GraphDef got Graph. for field Event.graph_def

**Comment by MorvanZhou** [comment]
请问你的 Tensorflow 的版本是哪个? 因为新版本的和老版本的语法有点不同.

**Comment by py060301045** [comment]
我用的是这个下的： https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl

**Comment by liuguiyangnwpu** [comment]
建议使用python3.x，我看莫凡老师使用的是python3.x @py060301045
